project:
  type: website
  output-dir: docs

website:
  title: "Web Anwendungen Übungen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "wöchentliche Übungen"
        menu:
          - href: u1/index.qmd
            text: "Übung 1: Setup & Basics"
          - href: u2/index.qmd
            text: "Übung 2: Node.js und Kommandozeile"
          - href: u3/index.qmd    
            text: "Übung 3: Arrays, Funktionen und mehr"
          - href: u4/index.qmd    
            text: "Übung 4: Strings, Datei und Datenbank"
          - href: u5/index.qmd    
            text: "Übung 5: Objektorientierung und AdonisJS"
          - href: u6/index.qmd    
            text: "Übung 6: AdonisJS und Datenbanken"
          - href: u7/index.qmd    
            text: "Übung 7: AdonisJS: Eine Todo-Liste"
          - href: u8/index.qmd    
            text: "Übung 8: AdonisJS: Sessions"
          - href: u9/index.qmd    
            text: "Übung 9: Grundlagen CSS"
          - href: u10/index.qmd    
            text: "Übung 10: Mehr CSS"
          - href: u11/index.qmd    
            text: "Übung 11: Adaptive und Responsive Web Design"
      - text: "Capstone Übungen"
        menu:
          - href: c1/index.qmd
            text: "C.1: Javascript Basics"
          - href: c2/index.qmd
            text: "C.2: AdonisJS"
          - href: c3/index.qmd
            text: "C.3: CSS"

format:
  html:
    theme: materia
    css: styles.css
    toc: true