project:
  type: website
  output-dir: docs

website:
  title: "Web Anwendungen Übungen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Cornerstone Übungen"
        menu:
          - href: cornerstone-1.qmd
            text: "C.1: Javascript Basics"

format:
  html:
    theme: materia
    css: styles.css
    toc: true